### ISSUE TITLE
The script doesn't run

### ISSUE THREAD

**Issue by michaelkruglos** [DominicBreuker/cryptanalysis#1]
Trying to run python main.py I get the following:
```
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    from breaking.caesar import CaesarBreak
ImportError: No module named breaking.caesar
```

**Comment by alabarre** [comment]
Different error here, but same issue:

~~~
$ python3 main.py 
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from pycipher import Caesar
ModuleNotFoundError: No module named 'pycipher'
~~~
